
#define CHUNK_BLOCKS 16
#define WORLD_CHUNKS 3
#define WORLD_BLOCKS ( WORLD_CHUNKS * CHUNK_BLOCKS )

#define BLOCK_SIZE 5.0f
#define CHUNK_SIZE ( BLOCK_SIZE * CHUNK_BLOCKS )
#define WORLD_SIZE ( CHUNK_SIZE * WORLD_CHUNKS )

#define BLOCK_VOLUME_SIZE ( BLOCK_SIZE * BLOCK_SIZE * BLOCK_SIZE )
#define CHUNK_VOLUME_SIZE ( CHUNK_SIZE * CHUNK_SIZE * CHUNK_SIZE )
#define WORLD_VOLUME_SIZE ( WORLD_SIZE * WORLD_SIZE * WORLD_SIZE )

#define CHUNK_BLOCKS_COUNT ( CHUNK_BLOCKS * CHUNK_BLOCKS * CHUNK_BLOCKS )
#define WORLD_BLOCKS_COUNT ( WORLD_BLOCKS * WORLD_BLOCKS * WORLD_BLOCKS )
#define WORLD_CHUNKS_COUNT ( WORLD_CHUNKS * WORLD_CHUNKS * WORLD_CHUNKS )