/*
#include "WorldDefs.hpp"

const uint32 CHUNK_BLOCKS = 16;
const uint32 WORLD_CHUNKS = 3;
const uint32 WORLD_BLOCKS = WORLD_CHUNKS * CHUNK_BLOCKS;

const float BLOCK_SIZE = 5.0f;
const float CHUNK_SIZE = BLOCK_SIZE * CHUNK_BLOCKS;
const float WORLD_SIZE = CHUNK_SIZE * WORLD_CHUNKS;

const float BLOCK_VOLUME_SIZE = ( BLOCK_SIZE * BLOCK_SIZE * BLOCK_SIZE );
const float CHUNK_VOLUME_SIZE = ( CHUNK_SIZE * CHUNK_SIZE * CHUNK_SIZE );
const float WORLD_VOLUME_SIZE = ( WORLD_SIZE * WORLD_SIZE * WORLD_SIZE );

const uint32 CHUNK_BLOCKS_COUNT = ( CHUNK_BLOCKS * CHUNK_BLOCKS * CHUNK_BLOCKS );
const uint32 WORLD_BLOCKS_COUNT = ( WORLD_BLOCKS * WORLD_BLOCKS * WORLD_BLOCKS );
const uint32 WORLD_CHUNKS_COUNT = ( WORLD_CHUNKS * WORLD_CHUNKS * WORLD_CHUNKS );*/
